//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya7
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Выбор размера.
    /// </summary>
    // *** Start programmer edit section *** (ВыборРазмера CustomAttributes)

    // *** End programmer edit section *** (ВыборРазмера CustomAttributes)
    public enum ВыборРазмера
    {
        
        // *** Start programmer edit section *** (ВыборРазмера.15х20 CustomAttributes)

        // *** End programmer edit section *** (ВыборРазмера.15х20 CustomAttributes)
        15х20,
        
        // *** Start programmer edit section *** (ВыборРазмера.20х30 CustomAttributes)

        // *** End programmer edit section *** (ВыборРазмера.20х30 CustomAttributes)
        20х30,
        
        // *** Start programmer edit section *** (ВыборРазмера.30х40 CustomAttributes)

        // *** End programmer edit section *** (ВыборРазмера.30х40 CustomAttributes)
        30х40,
        
        // *** Start programmer edit section *** (ВыборРазмера.10х15 CustomAttributes)

        // *** End programmer edit section *** (ВыборРазмера.10х15 CustomAttributes)
        10х15,
    }
}
